### ISSUE TITLE
Possible to get results to appear in base Alfred search results?

### ISSUE THREAD

**Issue by hbhargava7** [Stephen-Lon/Alfred-workflow-open-macos-13-settings-panes#4]
Prior to the MacOS 12/13 transition from System Preferences to System Settings, Alfred could search System Preferences (prefpanes) and include those results in the base search (or with the `find` keyword).

Is there a way to make the results of this workflow accessible in the main search? I.e. without any `syset` prefix

Thanks for a great tool!

**Comment by Stephen-Lon** [comment]
In the latest version of Alfred go to Alfred Preferences → Default Results and under `Applications: Options` check `Preferences` under `Essentials`. You should find that you can then use Alfred to search for most, if not all, of the preference panes in System Settings (i.e., without using my workflow). Alternatively, you may prefer [this workflow](https://alfred.app/workflows/alfredapp/system-settings/) (in the Alfred Gallery).

Thanks for your kind comment.
