### ISSUE TITLE
Add AppleCare & Warranty settings pane

### ISSUE THREAD

**Issue by FireFingers21** [Stephen-Lon/Alfred-workflow-open-macos-13-settings-panes#5]
In macOS Sonoma 14.1, a new `AppleCare & Warranty` settings pane was added under System Settings → General → AppleCare & Warranty. Its URL Scheme is `x-apple.systempreferences:com.apple.Coverage-Settings.extension`. Could it be added to the workflow?

**Comment by Stephen-Lon** [comment]
I could easily add that (I think) but at present am unable to discover whereabouts of the icon for the pane in order that can be used.

**Comment by FireFingers21** [comment]
I'm having the same problem, I posted a question on the forum asking about just that. I've been able to find a few pane icons scattered across the filesystem, but I'd have to imagine Vitor found a more straightforward way for his System Settings workflow.

**Comment by Stephen-Lon** [comment]
There is a resource file somewhere that contains the icons (not an obvious name at all) but, stupidly, I did not make a note of it and cannot now find it. I've searched a lot on the Net without success so we'll have to see if Vitor comes up with anything. (He is away just at the moment.)

**Comment by Stephen-Lon** [comment]
Thanks to Vitor's link in reply to your post on the forum I have the icon and will update the workflow and publish later in the day (slightly chaotic here at the moment!). 

For reference, the icon is at `/System/Library/ExtensionKit/Extensions/CoverageSettings.appex` and once you have that Vitor's "Get Info” trick works.
