### ISSUE TITLE
FR: add more broad keywords, e.g. `menu bar`

### ISSUE THREAD

**Issue by chrisgrieser** [Stephen-Lon/Alfred-workflow-open-macos-13-settings-panes#6]
What I like about this workflow is that it includes the various accessibility panes directly. Such a level of direct accessibility would also be useful for some other examples, such as when searching for the menu bar config. They do not have their own config (anymore), and simply adding `menubar` as a keyword to access them would be useful, I always struggle to find them.

**Comment by Stephen-Lon** [comment]
Sorry if I'm being obtuse but what do you expect to happen if a pane without its own config. (i.e., no programmatic access) is listed in the workflow? Are you, for example, suggesting that should open the System Settings pane with a search for that term completed? Again, sorry if I've misunderstood the suggestion!

**Comment by chrisgrieser** [comment]
It should open the pane where its related settings are located.

tbh, the only good one I can think of right now is `menubar`, which should open the control center pane.
![Pasted image 2024-08-23 at 11 04 03@2x](https://github.com/user-attachments/assets/2c0f8e87-039b-4b91-95de-e797c8884169)

**Comment by Stephen-Lon** [comment]
I think the difficulty with that is that (as you'll see if you scroll down through your search) that's not the only place where menu bar settings reside. Would it not be slightly misleading to have "Menu bar” open the Control Centre when someone in fact wants to show Input or a 24 hour clock on the menu bar, or to adjust the menu bar size? In other words, there is not only _one_ pane which includes menu bar settings. I know I'm playing devil's advocate but I just feel there's a risk of misleading people if we're not very careful.

**Comment by chrisgrieser** [comment]
> I think the difficulty with that is that (as you'll see if you scroll down through your search) that's not the only place where menu bar settings reside.

That argument applies to pretty much every item, though: There are Desktop-related settings not in the Desktop pane, there are keyboard-related settings not in the keyboard pane, etc. 

I'd say opening the pane the user *most likely* wants to open (90% of menubar related settings are in the control center pane) is still better than not having any pane for the keyword *at all*.

**Comment by Stephen-Lon** [comment]
Try version 2.6 just released.

**Comment by chrisgrieser** [comment]
Thank you!
